# Generated by Django 4.2 on 2023-10-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_emailentry_timestamp_emailentry_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailentry',
            name='name',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
